# maybe cache dependencies in the future https://github.com/actions/cache/blob/main/examples.md#python---pip
# Trigger the workflow on push or pull request
name: Python Linting with flake8
on: [push, pull_request]
jobs:
  run:
    name: Lint with flake8
    runs-on: ubuntu-latest
    steps:          
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: "load-cache"
        uses: actions/cache@master
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-flake8
      - name: Install dependencies
        if: steps.load-cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
